### ISSUE TITLE
Implement @media screen(sm)

### ISSUE THREAD

**Issue by nzakas** [humanwhocodes/tailwind-csstree#4]
```css
@media screen(sm) {
  .sidebar {
    display: none;
  }
}

@media screen(md) {
  .container {
    max-width: theme(screens.md);
  }
}
```

See:
https://v3.tailwindcss.com/docs/functions-and-directives#screen
